version: "3.9"

services:
    api:
        build: 
          context: .
          dockerfile: real-time-broker/Dockerfile
        ports:
            - "5000:80"
    app:
        build: 
            context: .
            dockerfile: dashboard-app/Dockerfile
        ports:
            - "4200:80"